author: 'Ricardo SIGNES <rjbs@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Email-Simple-FromHandle
no_index:
  directory:
    - inc
    - t
requires:
  Email::Simple: 1.9
  IO::String: 0
version: 0.011
